"""empty message

Revision ID: 857f078ada5c
Revises: e6443da08179
Create Date: 2021-03-18 11:58:37.159333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857f078ada5c'
down_revision = 'e6443da08179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
